#!/usr/bin/env bash

nick="$(basename $0)"
host="$1"
port="$2"
chan="#$3"

if [ ! "$3" ]; then
	echo "usage: $(basename $0) host port chan"
	exit 1
fi

if ! exec 3<> /dev/tcp/$host/$port; then
	echo "$(basename $0): unable to connect to $host:$port"
	exit 1
fi

exec <&3 >&3-

echo "USER $nick $nick $nick :$nick"
echo "NICK $nick"
echo "JOIN $chan"

while read line; do
	[[ "$line" =~ ^PING\ :(.*)$ ]] && echo "PONG :${BASH_REMATCH[1]}"
	
	if [[ "$line" =~ ^:([^ ]*)\ ([^\ ]*)\ ([^:]*)(\ :(.*))?$ ]]; then
		sender=${BASH_REMATCH[1]%\!*}
		server=${BASH_REMATCH[1]#*\!}
		command=${BASH_REMATCH[2]}
		args=(${BASH_REMATCH[3]})
		contents=${BASH_REMATCH[5]%?}

		case $command in
		KICK) [[ ${args[1]} == $nick ]] && echo "JOIN ${args[0]}" ;;
		PART) [[ $sender == $nick ]] && echo "JOIN ${args[0]}" ;;
		MODE)
		# :JoshDreamland!~josh@d118-75-93-174.try.wideopenwest.com MODE #enigma-dev +b bobbbb!*@* 
			if [[ "${args[1]}" =~ ^\+[bq] && $nick =~ ${args[2]%\!*} ]]; then
				nick="$(basename $0)$RANDOM"
				echo "PART ${args[0]}"
				echo "NICK $nick"
				echo "JOIN ${args[0]}"
			fi

			# todo: fix the holes here
			#elif [[ "${args[1]}" =~ ^\-[bq] && $(basename $0) =~ ${args[2]%\!*} ]]; then
			#	nick="$(basename $0)"
			#	echo "NICK $nick"
			;;
		474)
		# :leguin.freenode.net 474 bobbbb #enigma-dev :Cannot join channel (+b) - you are banned
			nick="$(basename $0)$RANDOM"
			echo "NICK $nick"
			echo "JOIN ${args[1]}"
			;;

		PRIVMSG)
			[[ ${args[0]} == $chan ]] && echo "$contents" >> "logs/$sender"

			if [[ "$contents" =~ ^\!(.*) ]]; then
				cmd=${BASH_REMATCH[1]%%\ *}
				cmdargs=${BASH_REMATCH[1]#*\ }

				case $cmd in
				mock)
					name=${cmdargs//[^-a-zA-Z0-9\[\]\\\`_^\{\}|]}
					if [ -e "logs/$name" ]; then
						text=$(./markov -d 1 -n 20 < "logs/$name" | tr '\r\n' ' ' | tr -s ' ')
						echo "PRIVMSG $chan :\"$text\" -- $name"
					else
						echo "PRIVMSG $chan :I've never heard of $name"
					fi
					;;

				say)
					echo "PRIVMSG $chan :${cmdargs}"
					;;
				msg)
					echo "PRIVMSG ${cmdargs%%\ *} :${cmdargs#*\ }"
					;;
				me)
					echo "PRIVMSG $chan :ACTION ${cmdargs}"
					;;

				nick)
					nick=${cmdargs//[^-a-zA-Z0-9\[\]\\\`_^\{\}|]}
					echo "NICK $nick"
					;;
				esac
			fi
			;;
		esac
	fi
done
